/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 src/assets/models/volcano2.glb 
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import baseScene from "../assets/models/Volcano2.glb";

export function Volcano2({ props, position }) {
  const { nodes, materials } = useGLTF(baseScene);
  return (
    <group
      {...props}
      dispose={null}
      position={position}
      scale={[8.99, 7.99, 6.1642]}
    >
      <mesh
        geometry={nodes.Plane001.geometry}
        material={materials["Black rock"]}
        position={[0, 0.142, 0]}
        scale={[1, 0.557, 1]}
      />
      <mesh
        geometry={nodes.Plane019.geometry}
        material={materials.Portal}
        position={[-1.374, 3.374, -29.714]}
        rotation={[0, Math.PI / 2, 0]}
        scale={0.601}
      />
      <mesh
        geometry={nodes.Plane018.geometry}
        material={materials["Black rock"]}
        position={[-1.253, 3.507, -29.675]}
        rotation={[0, Math.PI / 2, 0]}
        scale={0.578}
      />
      <mesh
        geometry={nodes.Plane017.geometry}
        material={materials["Black rock"]}
        position={[-1.382, 3.678, -29.674]}
        rotation={[0, Math.PI / 2, 0]}
        scale={0.578}
      />
      <mesh
        geometry={nodes.Cube.geometry}
        material={materials["Black rock"]}
        position={[-1.38, 1.946, -29.714]}
        rotation={[0, Math.PI / 2, 0]}
        scale={0.578}
      />
      <mesh
        geometry={nodes.Hair_Base_001001.geometry}
        material={materials["A_Hair.002"]}
      />
      <mesh
        geometry={nodes.Glove_002001.geometry}
        material={materials["Glove_002.001"]}
      />
      <mesh
        geometry={nodes.Rock_4_Rock_4_0.geometry}
        material={materials["Black rock"]}
        position={[5.229, 0.512, -1.545]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.65}
      />
      <mesh
        geometry={nodes.Rock_5_Rock_5_0.geometry}
        material={materials["Black rock"]}
        position={[9.536, 0.24, -2.749]}
        rotation={[-Math.PI / 2, 0, 1.031]}
        scale={[0.47, 0.47, 0.142]}
      />
      <mesh
        geometry={nodes.Rock_6_Rock_6_0.geometry}
        material={materials["Black rock"]}
        position={[8.01, 1.954, -14.497]}
        rotation={[-Math.PI / 2, 0, -2.455]}
        scale={[0.31, 0.65, 1.826]}
      />
      <mesh
        geometry={nodes.Rock_1_Rock_1_0.geometry}
        material={materials["Black rock"]}
        position={[-7.727, -0.057, -3.616]}
        rotation={[-Math.PI / 2, 0, 1.853]}
        scale={0.65}
      />
      <mesh
        geometry={nodes.Rock_2_Rock_2_0.geometry}
        material={materials["Black rock"]}
        position={[7.702, 2.421, -8.226]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={3.514}
      />
      <mesh
        geometry={nodes.Rock_3_Rock_3_0.geometry}
        material={materials["Black rock"]}
        position={[6.532, 2.28, -20.048]}
        rotation={[-1.793, -0.107, 1.383]}
        scale={[1.757, 1.758, 0.892]}
      />
      <mesh
        geometry={nodes.Rock_3_Rock_3_0001.geometry}
        material={materials["Black rock"]}
        position={[-9.678, 2.28, -18.343]}
        rotation={[-1.723, -0.195, 1.84]}
        scale={[1.757, 1.758, 0.892]}
      />
      <mesh
        geometry={nodes.Rock_2_Rock_2_0001.geometry}
        material={materials["Black rock"]}
        position={[5.717, 2.421, -27.414]}
        rotation={[-Math.PI / 2, 0, 0.748]}
        scale={3.514}
      />
      <mesh
        geometry={nodes.Rock_7_Rock_7_0001.geometry}
        material={materials["Black rock"]}
        position={[-5.558, 2.169, -15.535]}
        rotation={[-Math.PI / 2, 0, -0.23]}
        scale={[0.386, 1.011, 1.838]}
      />
      <mesh
        geometry={nodes.Rock_13_Rock_13_0001.geometry}
        material={materials["Black rock"]}
        position={[-4.184, 0.897, -12.05]}
        rotation={[-1.719, -0.022, 1.307]}
        scale={[0.65, 0.65, 0.323]}
      />
      <mesh
        geometry={nodes.Rock_13_Rock_13_0002.geometry}
        material={materials["Black rock"]}
        position={[-3.143, 0.897, -17.87]}
        rotation={[-1.719, -0.022, 1.307]}
        scale={[0.65, 0.65, 0.323]}
      />
      <mesh
        geometry={nodes.Rock_13_Rock_13_0003.geometry}
        material={materials["Black rock"]}
        position={[-3.572, 0.897, -20.076]}
        rotation={[-1.719, -0.022, 1.307]}
        scale={[0.65, 0.65, 0.323]}
      />
      <mesh
        geometry={nodes.Rock_7_Rock_7_0002.geometry}
        material={materials["Black rock"]}
        position={[5.013, 2.169, -3.188]}
        rotation={[-Math.PI / 2, 0, -1.036]}
        scale={[0.386, 1.011, 1.838]}
      />
      <mesh
        geometry={nodes.Rock_10_Rock_10_0001.geometry}
        material={materials["Black rock"]}
        position={[-1.288, 0.142, -8.517]}
        rotation={[-Math.PI / 2, 0, 1.294]}
        scale={[0.65, 0.65, 0.289]}
      />
      <mesh
        geometry={nodes.Rock_11_Rock_11_0001.geometry}
        material={materials["Black rock"]}
        position={[-3.668, 0.207, 0.597]}
        rotation={[-Math.PI / 2, 0, 1.294]}
        scale={[0.65, 0.65, 0.289]}
      />
      <mesh
        geometry={nodes.Rock_15_Rock_15_0001.geometry}
        material={materials["Black rock"]}
        position={[4.423, 0.64, -26.092]}
        rotation={[-Math.PI / 2, 0, 1.294]}
        scale={[0.65, 0.65, 0.289]}
      />
      <mesh
        geometry={nodes.Rock_3_Rock_3_0002.geometry}
        material={materials["Black rock"]}
        position={[-9.954, 2.28, -26.364]}
        rotation={[-1.703, -0.209, 1.943]}
        scale={[1.757, 1.758, 0.892]}
      />
      <mesh
        geometry={nodes.Rock_10_Rock_10_0002.geometry}
        material={materials["Rock.002"]}
        position={[-1.33, 0.165, -25.746]}
        scale={[1.083, 0.354, 0.512]}
      />
      <mesh
        geometry={nodes.Rock_4_Rock_4_0001.geometry}
        material={materials["Black rock"]}
        position={[-3.782, 1.279, -29.66]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={1.127}
      />
      <mesh
        geometry={nodes.Rock_2_Rock_2_0003.geometry}
        material={materials["Black rock"]}
        position={[-7.138, 3.042, -30.324]}
        rotation={[-Math.PI / 2, 0, 2.202]}
        scale={3.514}
      />
      <mesh geometry={nodes.Plane.geometry} material={materials.Material} />
      <mesh
        geometry={nodes.Liquid_Domain.geometry}
        material={materials.Material}
        position={[-8.431, 7.942, -18.593]}
        scale={[3.541, 4.296, 2.374]}
      />
      <mesh
        geometry={nodes.Liquid_Domain001.geometry}
        material={materials.Material}
        position={[4.653, 8.401, -28.463]}
        scale={[2, 3, 2]}
      />
      <mesh
        geometry={nodes.Liquid_Domain002.geometry}
        material={materials.Material}
        position={[-9.319, 9.526, -11.78]}
        scale={[1.627, 2.627, 1.627]}
      />
      <mesh
        geometry={nodes.Liquid_Domain003.geometry}
        material={materials.Material}
        position={[4.653, 8.401, -28.463]}
        scale={[2, 3, 2]}
      />
      <mesh
        geometry={nodes.CC_Base_Eye_003001_1.geometry}
        material={materials["Std_Eye_R_002.001"]}
      />
      <mesh
        geometry={nodes.CC_Base_Eye_003001_2.geometry}
        material={materials["Std_Cornea_R_002.001"]}
      />
      <mesh
        geometry={nodes.CC_Base_Eye_003001_3.geometry}
        material={materials["Std_Eye_L_002.001"]}
      />
      <mesh
        geometry={nodes.CC_Base_Eye_003001_4.geometry}
        material={materials["Std_Cornea_L_002.001"]}
      />
      <mesh
        geometry={nodes.Camila_Brow_001001_1.geometry}
        material={materials["Female_Brow_Transparency_001.001"]}
      />
      <mesh
        geometry={nodes.Camila_Brow_001001_2.geometry}
        material={materials["Female_Brow_Base_Transparency_001.001"]}
      />
    </group>
  );
}

useGLTF.preload("/volcano2.glb");
