/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/Volcano.glb 
*/

import { useAnimations, useGLTF } from "@react-three/drei";
import baseScene from "../assets/models/Volcano.glb";
import React, { useEffect } from "react";
import { useRef } from "react";

export function Volcano(props) {
  const group = useRef();

  const { nodes, materials, animations } = useGLTF(baseScene);
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    console.log(actions);
    // actions.walking.play();
  });

  return (
    <group
      {...props}
      dispose={null}
      position={[5.229, -26.2, -5.545]}
      scale={[8.99, 7.99, 6.1642]}
      // rotation={[2 * Math.PI, 0, 6.25]}
      // position={[0, -4.25, -1.5]}
    >
      <mesh
        geometry={nodes.Rock_4_Rock_4_0.geometry}
        material={materials["Black rock"]}
        position={[5.229, 0.512, -1.545]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.65}
      />
      <mesh
        geometry={nodes.Rock_5_Rock_5_0.geometry}
        material={materials["Black rock"]}
        position={[9.536, 0.24, -2.749]}
        rotation={[-Math.PI / 2, 0, 1.031]}
        scale={[2.47, 0.47, 0.142]}
      />
      <mesh
        geometry={nodes.Rock_6_Rock_6_0.geometry}
        material={materials["Black rock"]}
        position={[8.01, 1.954, -14.497]}
        rotation={[-Math.PI / 2, 0, -2.455]}
        scale={[0.31, 0.65, 1.826]}
      />
      <mesh
        geometry={nodes.Rock_1_Rock_1_0.geometry}
        material={materials["Black rock"]}
        position={[-7.727, -0.057, -3.616]}
        rotation={[-Math.PI / 2, 0, 1.853]}
        scale={0.65}
      />
      <mesh
        geometry={nodes.Rock_2_Rock_2_0.geometry}
        material={materials["Black rock"]}
        position={[7.702, 2.421, -8.226]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={3.514}
      />
      <mesh
        geometry={nodes.Rock_3_Rock_3_0.geometry}
        material={materials["Black rock"]}
        position={[6.532, 2.28, -20.048]}
        rotation={[-1.793, -0.107, 1.383]}
        scale={[1.757, 1.758, 0.892]}
      />
      <mesh
        geometry={nodes.Rock_3_Rock_3_0001.geometry}
        material={materials["Black rock"]}
        position={[-9.678, 2.28, -18.343]}
        rotation={[-1.723, -0.195, 1.84]}
        scale={[1.757, 1.758, 0.892]}
      />
      <mesh
        geometry={nodes.Rock_5_Rock_5_0001.geometry}
        material={materials["Black rock"]}
        position={[1.081, 0.24, -23.554]}
        rotation={[-Math.PI / 2, 0, 1.031]}
        scale={[0.47, 0.47, 0.142]}
      />
      <mesh
        geometry={nodes.Rock_2_Rock_2_0001.geometry}
        material={materials["Black rock"]}
        position={[5.717, 2.421, -27.414]}
        rotation={[-Math.PI / 2, 0, 0.748]}
        scale={3.514}
      />
      <mesh
        geometry={nodes.Rock_7_Rock_7_0001.geometry}
        material={materials["Black rock"]}
        position={[-5.558, 2.169, -15.535]}
        rotation={[-Math.PI / 2, 0, -0.23]}
        scale={[0.386, 1.011, 1.838]}
      />
      <mesh
        geometry={nodes.Rock_13_Rock_13_0001.geometry}
        material={materials["Black rock"]}
        position={[-4.184, 0.897, -12.05]}
        rotation={[-1.719, -0.022, 1.307]}
        scale={[0.65, 0.65, 0.323]}
      />
      <mesh
        geometry={nodes.Rock_13_Rock_13_0002.geometry}
        material={materials["Black rock"]}
        position={[-3.143, 0.897, -17.87]}
        rotation={[-1.719, -0.022, 1.307]}
        scale={[0.65, 0.65, 0.323]}
      />
      <mesh
        geometry={nodes.Rock_13_Rock_13_0003.geometry}
        material={materials["Black rock"]}
        position={[-3.572, 0.897, -20.076]}
        rotation={[-1.719, -0.022, 1.307]}
        scale={[0.65, 0.65, 0.323]}
      />
      <mesh
        geometry={nodes.Rock_7_Rock_7_0002.geometry}
        material={materials["Black rock"]}
        position={[5.013, 2.169, -3.188]}
        rotation={[-Math.PI / 2, 0, -1.036]}
        scale={[0.386, 1.011, 1.838]}
      />
      <mesh
        geometry={nodes.Rock_10_Rock_10_0001.geometry}
        material={materials["Black rock"]}
        position={[-1.288, 0.142, -8.517]}
        rotation={[-Math.PI / 2, 0, 1.294]}
        scale={[0.65, 0.65, 0.289]}
      />
      <mesh
        geometry={nodes.Rock_11_Rock_11_0001.geometry}
        material={materials["Black rock"]}
        position={[-3.668, 0.207, 0.597]}
        rotation={[-Math.PI / 2, 0, 1.294]}
        scale={[0.65, 0.65, 0.289]}
      />
      <mesh
        geometry={nodes.Rock_15_Rock_15_0001.geometry}
        material={materials["Black rock"]}
        position={[4.423, 0.64, -26.092]}
        rotation={[-Math.PI / 2, 0, 1.294]}
        scale={[0.65, 0.65, 0.289]}
      />
      <mesh
        geometry={nodes.Rock_14_Rock_14_0001.geometry}
        material={materials["Black rock"]}
        position={[2.237, 0.452, -19.894]}
        rotation={[-Math.PI / 2, 0, 1.294]}
        scale={[0.65, 0.65, 0.289]}
      />
      <mesh
        geometry={nodes.Rock_3_Rock_3_0002.geometry}
        material={materials["Black rock"]}
        position={[-9.954, 2.28, -26.364]}
        rotation={[-1.703, -0.209, 1.943]}
        scale={[1.757, 1.758, 0.892]}
      />
      <mesh
        geometry={nodes.Rock_10_Rock_10_0002.geometry}
        material={materials["Rock.002"]}
        position={[-1.33, 0.165, -25.746]}
        scale={[1.083, 0.354, 0.512]}
      />
      <mesh
        geometry={nodes.Rock_4_Rock_4_0001.geometry}
        material={materials["Black rock"]}
        position={[-3.782, 1.279, -29.66]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={1.127}
      />
      <mesh
        geometry={nodes.Rock_2_Rock_2_0002.geometry}
        material={materials["Black rock"]}
        position={[5.839, 3.042, -28.683]}
        rotation={[-Math.PI / 2, 0, 2.123]}
        scale={3.514}
      />
      <mesh
        geometry={nodes.Rock_2_Rock_2_0003.geometry}
        material={materials["Black rock"]}
        position={[-7.138, 3.042, -30.324]}
        rotation={[-Math.PI / 2, 0, 2.202]}
        scale={3.514}
      />
      <mesh geometry={nodes.Plane.geometry} material={materials.VOLCANO} />
      <mesh
        geometry={nodes.Plane001.geometry}
        material={materials["Black rock"]}
        position={[0, 0.142, 0]}
        scale={[1, 0.557, 1]}
      />
      <mesh
        geometry={nodes.Plane019.geometry}
        material={materials.Portal}
        position={[-1.374, 3.374, -29.714]}
        rotation={[0, Math.PI / 2, 0]}
        scale={0.601}
      />
      <mesh
        geometry={nodes.Plane018.geometry}
        material={materials["Black rock"]}
        position={[-1.253, 3.507, -29.675]}
        rotation={[0, Math.PI / 2, 0]}
        scale={0.578}
      />
      <mesh
        geometry={nodes.Plane017.geometry}
        material={materials["Black rock"]}
        position={[-1.382, 3.678, -29.674]}
        rotation={[0, Math.PI / 2, 0]}
        scale={0.578}
      />
      <mesh
        geometry={nodes.Cube.geometry}
        material={materials["Black rock"]}
        position={[-1.38, 1.946, -29.714]}
        rotation={[0, Math.PI / 2, 0]}
        scale={0.578}
      />
      <mesh geometry={nodes.Plane002.geometry} material={materials.VOLCANO} />
      <mesh
        geometry={nodes.Plane003.geometry}
        material={materials.VOLCANO}
        position={[-8.23, 6.471, -20.032]}
        rotation={[0, -0.974, 0]}
      />
      <mesh
        geometry={nodes.Plane004.geometry}
        material={materials.VOLCANO}
        position={[8.942, 6.927, -19.763]}
        rotation={[Math.PI, -0.466, Math.PI]}
      />
      <mesh
        geometry={nodes.Plane005.geometry}
        material={materials.VOLCANO}
        position={[8.119, 6.927, -8.441]}
        rotation={[Math.PI, -0.466, Math.PI]}
      />
    </group>
  );
}

useGLTF.preload("/Volcano.glb");
